title: "RishBlogs"
author: "Rishabh Singhal"
#description: "Made with <b style=\"color: #f45;\">&lt;3</b> by <b><a href=\"https://github.com/rish-singhal\">@rish-singhal</a></b>"
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true

sidebar: false            # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: false       # show the site description in the sidebar
show_title: true            # always keep the site title visible
mathjax: true

# Styling

dark_header: false      # always keep the header dark
minimal: true           # use simpler style

# Menu

navigation:
  - {title: Home, icon: link, url: "https://rish-singhal.github.io"}
  - {file: "index.html", icon: home}
  - {file: "about_me.md", icon: address-card}
  - {file: "resources.md", icon: list}
#  - {title: Resume, icon: link, url: "https://github.com/rish-singhal/Resume/blob/main/resume_rishabh_singhal.pdf"}

external:                    # see http://fontawesome.com/icons
 - {title: Mail, icon: envelope, url: "mailto:rishabh.singhal@research.iiit.ac.in"}
 - {title: Github, icon: github, url: "https://github.com/rish-singhal"}
 - {title: Subscribe, icon: rss, url: "/feed.xml"}

# comments:
disqus_shortname: "rishblogs"     # see https://disqus.com/
# #  isso_domain: ""           # see https://posativ.org/isso/

plugins:
 - jekyll-feed
